### PR TITLE
Add the ability to pull recipes from a private github repo

### PR DESCRIPTION
**Pull request by tugboat**
What's up folks.  I really want to be able to make the sunzi-recipes repo private to avoid the issue I ran into over the weekend.  Right now it's public so we can't commit any secrets into the repo and it can be hard to make sure that happens.  

With this change we can define github info in our sunzi.yml file like so: 

```yaml
---
github:
  organization: 'metabahn'
  repository: 'sunzi-recipes'
  access_token: '<github-access-token>'
```

Then we are able to reference our private recipes like so:
```yaml
private_recipes:
  - sunzi
  - hostname
  - hosts
```

And it downloads and compiles them in the same way that the public recipes are handled.

### CODE REVIEW

**Comment by bryanp** [comment]
Fetching an access key is an extra step. It might be necessary here, but I'll throw this out there. 

Chat if we used public key auth? Not sure how these recipes are fetched but if it could be done via ssh we could forward the keys and have things just work, so long as the current user had access to the repo. Also more secure in that if someone got the code they still couldn't access our recipes (because no access code).

Thoughts?

**Comment by tugboat** [comment]
That definitely sounds possible.  Let me think about that a little bit.  It would be really cool to do it that way since we are all already using public keys for git anyway.

**Comment by bryanp** [comment]
I am needing this (all your PRs actually) so I say we use as-is and change later.

**Comment by bryanp** [comment]
I changed this to not use github creds. It relies on a new `private_recipes_repo` preference.

**Pull request merged**
