### PR TITLE
Compile files from a remote repo

### PR DESCRIPTION
**Pull request by bryanp**
- When preferences.remote_files if a valid git repo, sunzi will clone the repo and compile all the files in it to compiled/files
- If a local file exists, that the local one overrides the remote one
- Remote files have access to attributes, just like local ones

This sets us up for something I'll show you in my next PR over in `sunzi-recipes` :-)

### CODE REVIEW

**Comment by bryanp** [comment]
So let me lay out the reasoning behind this. I've been a bit overwhelmed when spinning up new nodes that are identical to existing nodes, with only minor config differences. We have to make sure and move the config files over, etc. This came up again when creating the postgres standby for the private HAIB cluster.

After a bit of thinking, I realized that we can abstract the files to sane defaults and allow local overrides for the few and far between exception cases. Most of the time we can do what we want with config values. When we can't, make a local override and do what you want.

I believe this will drastically simplify all of our sunzi server repos. Eager for feedback 😀

**Comment by bryanp** [comment]
Oh, and this also demonstrates the approach I had in mind with using a private key to fetch a recipe instead of embedding a token. A difference is that we don't want to include all recipes, only specific ones. Actually, maybe that's the case with files too?

**Comment by dgmcguire** [comment]
huge fan and seems to solve the biggest concern I had for using sunzi

👍 👍 👍

**Comment by tugboat** [comment]
This looks like it shares some functionality with #2 , is this one in place of that work or am I reading it wrong?

**Comment by bryanp** [comment]
@tugboat #2 if for private *remote recipes*, this is for *remote files*.

**Pull request merged**
